### PR TITLE
create database and tables with examples

### PR DESCRIPTION
**Pull request by fredl2tp**
Create database and tables with examples.

### CODE REVIEW

**Review by Christophe-76 — APPROVED** [review]

**Review by Eric-Rouviere — APPROVED** [review]
Check ok

**Review by RolandEsnay — APPROVED** [review]
Check OK

**Review by Christophe-76 — APPROVED** [review]
check ok

**Review by RolandEsnay — APPROVED** [review]

**Review by Eric-Rouviere — APPROVED** [review]
Remember change language to french please check all requests

**Pull request merged**
